version: '2.4'

services:

  backend-nodejs:
    container_name: backend-nodejs
    build: ./docker/nodejs
    env_file:
      - .env
    depends_on:
      - backend-postgres
      - backend-redis
    ports:
      - ${APP_PUBLIC_PORT}:${APP_PUBLIC_PORT}
    restart: always
    networks:
      - backend-network
    ulimits:
      nofile:
        soft: 128000
        hard: 128000

  backend-postgres:
    container_name: backend-postgres
    build: ./docker/postgres
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker-data/postgres/data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend-network
    ulimits:
      nofile:
        soft: 128000
        hard: 128000

  backend-redis:
    container_name: backend-redis
    image: redis:latest
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - backend-network
    ulimits:
      nofile:
        soft: 128000
        hard: 128000

networks:
  backend-network:
    external: true
